const initialValuesContenidoAjeno = {
  informeDeLecturaRol: false,
  correccionGramaticalRol: false,
  correccionEstilosRol: false,
  edicionMaquetacionRol: false,
  disenioImagenesRol: false,
  traducirRol: false,
  rolAutorEnLaObra: "",
  reconocimientoAutor: "",
  acuerdoComercialNoAutor: "",
  acuerdoComercialNoAutorPorcentaje: "",
  contanosMas: "",
  etapaDesarrollo: "",
  informeDeLectura: false,
  correccionGramatical: false,
  correccionEstilos: false,
  edicionMaquetacion: false,
  disenioImagenes: false,
  arteTapa: false,
  todoListo: false,
  traducir: false,
  idiomaOriginal: "",
  idiomaATraducir: "",
  limitacionesPresupuestarias: "",
  distribucionLibro: "",
  tipoDistribucion: "",
};

export { initialValuesContenidoAjeno };
